'use strict';

/**
 * Static module reachability for src/: follows every literal relative require (lazy ones included) from the roots and
 * writes a markdown report. Usage: node tools/dev/reachability.js <out.md> [label]
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const SRC = path.join(ROOT, 'src');
const ROOTS = { 'bin/lain.js': path.join(ROOT, 'bin', 'lain.js'), 'src/app.js': path.join(SRC, 'app.js'), 'src/turn.js': path.join(SRC, 'turn.js') };

function walk(d, out = []) {
  for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p, out); else if (e.name.endsWith('.js')) out.push(p);
  }
  return out;
}
function lines(f) { return fs.readFileSync(f, 'utf8').split('\n').length; }
function resolve(from, spec) {
  const base = path.resolve(path.dirname(from), spec);
  for (const c of [base, `${base}.js`, path.join(base, 'index.js')]) if (fs.existsSync(c) && fs.statSync(c).isFile()) return c;
  return null;
}
const edges = new Map();
function depsOf(f) {
  if (edges.has(f)) return edges.get(f);
  const text = fs.readFileSync(f, 'utf8');
  const out = new Set();
  for (const m of text.matchAll(/require\(\s*(['"`])(\.{1,2}\/[^'"`$]+)\1\s*\)/g)) { const r = resolve(f, m[2]); if (r && r.endsWith('.js')) out.add(r); }
  edges.set(f, out);
  return out;
}
function reach(start) {
  const seen = new Set([start]);
  const q = [start];
  while (q.length) for (const d of depsOf(q.shift())) if (!seen.has(d)) { seen.add(d); q.push(d); }
  return seen;
}

const all = walk(SRC);
const rel = (f) => path.relative(ROOT, f).replace(/\\/g, '/');
const sum = (set) => [...set].filter((f) => f.startsWith(SRC)).reduce((n, f) => n + lines(f), 0);
const R = Object.fromEntries(Object.entries(ROOTS).map(([k, f]) => [k, reach(f)]));
const fromBin = R['bin/lain.js'];
const unreachable = all.filter((f) => !fromBin.has(f));
const totalLines = all.reduce((n, f) => n + lines(f), 0);

const out = process.argv[2] || path.join(ROOT, 'docs', 'simplify', 'reachability.md');
const label = process.argv[3] || 'snapshot';
const md = [
  `# Reachability — ${label}`, '',
  `Generated by \`tools/dev/reachability.js\` (static literal \`require\` scan, lazy requires included) on ${new Date().toISOString().slice(0, 10)}.`, '',
  '| Set | Modules | Lines |', '|---|---:|---:|',
  `| all of src/ | ${all.length} | ${totalLines} |`,
  ...Object.entries(R).map(([k, s]) => `| reachable from ${k} | ${[...s].filter((f) => f.startsWith(SRC)).length} | ${sum(s)} |`),
  `| unreachable from bin/lain.js | ${unreachable.length} | ${unreachable.reduce((n, f) => n + lines(f), 0)} |`, '',
  '## The turn path (reachable from src/turn.js), largest first', '',
  ...[...R['src/turn.js']].filter((f) => f.startsWith(SRC)).sort((a, b) => lines(b) - lines(a)).map((f) => `- ${rel(f)} (${lines(f)})`), '',
  '## Unreachable from bin/lain.js', '',
  ...(unreachable.length ? unreachable.sort().map((f) => `- ${rel(f)} (${lines(f)})`) : ['- none']), '',
];
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, md.join('\n'));
console.log(JSON.stringify({ all: all.length, totalLines, ...Object.fromEntries(Object.entries(R).map(([k, s]) => [k, [...s].filter((f) => f.startsWith(SRC)).length])), unreachable: unreachable.length }));
